spring:
  redis:
    host: 127.0.0.1
    database: 0
    password:
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 200
        max-wait: 1000
        min-idle: 5
    timeout: 100